library(shiny)
library(dplyr)
library(ggplot2)
library(dygraphs)
library(gridExtra)
library(rlist)
library(shinydashboard)
library(plotly)

df <- read.csv("New_York_City_Leading_Causes_of_Death.csv")
df <- df[-c(1097,1096,1095), ]

# Converting factors to characters and numerics
df$Deaths <- as.numeric(as.character(df$Deaths))
df$Death.Rate <- as.numeric(as.character(df$Death.Rate))
df$Age.Adjusted.Death.Rate <- as.numeric(as.character(df$Age.Adjusted.Death.Rate))
df$Year <- as.numeric(as.character(df$Year))
df$Leading.Cause <-(as.character(df$Leading.Cause))
df$Sex <-(as.character(df$Sex))
df$Race.Ethnicity <-as.character(df$Race.Ethnicity)
df$Leading.Cause = substr(df$Leading.Cause, 1,15)

o = df %>% group_by (Year) %>% summarise(Total = sum(Death.Rate, na.rm = TRUE))
o1 = df %>% group_by (Year) %>% summarise(Total1 = sum(Age.Adjusted.Death.Rate, na.rm = TRUE))
Overview <- cbind(o, o1)
sub <- subset(df, Race.Ethnicity != "Other Race/ Ethnicity" & Race.Ethnicity != "Not Stated/Unknown", select = c("Year","Leading.Cause", "Race.Ethnicity","Sex", "Deaths", "Death.Rate", "Age.Adjusted.Death.Rate"))
his_sub <- subset(df, Race.Ethnicity == "Hispanic", select = c("Year","Leading.Cause", "Race.Ethnicity","Sex", "Deaths", "Death.Rate","Age.Adjusted.Death.Rate"))
a_sub <- subset(df, Race.Ethnicity == "Asian and Pacific Islander", select = c("Year","Leading.Cause", "Race.Ethnicity","Sex", "Deaths", "Death.Rate","Age.Adjusted.Death.Rate"))
w_sub <- subset(df, Race.Ethnicity == "White Non-Hispanic", select = c("Year","Leading.Cause", "Race.Ethnicity","Sex", "Deaths", "Death.Rate","Age.Adjusted.Death.Rate"))
b_sub <- subset(df, Race.Ethnicity == "Black Non-Hispanic", select = c("Year","Leading.Cause", "Race.Ethnicity","Sex", "Deaths", "Death.Rate","Age.Adjusted.Death.Rate"))
o_sub <- subset(df, Race.Ethnicity == "Other Race/ Ethnicity", select = c("Year","Leading.Cause", "Race.Ethnicity","Sex", "Deaths", "Death.Rate","Age.Adjusted.Death.Rate"))
heart_sub <- subset(df, Leading.Cause == "Diseases of Hea", select = c("Year","Leading.Cause", "Race.Ethnicity","Sex", "Deaths", "Death.Rate","Age.Adjusted.Death.Rate"))
cancer_sub <- subset(df, Leading.Cause == "Malignant Neopl", select = c("Year","Leading.Cause", "Race.Ethnicity","Sex", "Deaths", "Death.Rate","Age.Adjusted.Death.Rate"))